version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: users-api
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - users-api

    nginx:
        image: nginx:alpine
        container_name: users-api-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - users-api

networks:
    users-api:
        driver: bridge 